---
server:
  port: 9001
  contextPath: /demo3custapp
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/authserver/user 
